# Generated by Django 6.1 on 2026-08-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0004_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('backup_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('source_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='clusters.app')),
            ],
        ),
    ]
