# Generated by Django 6.1 on 2026-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='server_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='description',
        ),
        migrations.AddField(
            model_name='cluster',
            name='token',
            field=models.TextField(default='temp_token'),
            preserve_default=False,
        ),
    ]
