# Generated by Django 6.1 on 2026-08-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='disk',
            field=models.CharField(default='1Gi', max_length=50),
        ),
    ]
